/**
 * Trigger layer types.
 *
 * A trigger is a long-lived source that emits ceremony requests into the daemon
 * in response to external signals:
 *   - HTTP/IPC: operator POSTs JSON to a local endpoint.
 *   - Cron: wall-clock schedule fires a named job.
 *
 * Chain-watching is intentionally out of scope — the daemon is a signing
 * backend, not an autonomous chain observer. Operator infrastructure that
 * needs an event-driven flow watches the chain itself and POSTs `/sign`.
 *
 * Triggers themselves do NOT know about ceremonies, shares, or the gate. They
 * deliver typed events to caller-supplied handlers. The daemon entrypoint
 * (phase 5e) wires the handlers — turning an HTTP request or cron tick into a
 * leader-side ceremony: gate eval → `signAsLeader` / `runDkg` → broadcast.
 *
 * Keeping trigger sources handler-agnostic lets tests exercise them in
 * isolation and lets future trigger kinds slot in without changing the daemon
 * entrypoint signature.
 */

import type { Logger } from '../orchestrator/types';

// ─────────────────────────────────────────────────────────────────────────
// HTTP trigger
// ─────────────────────────────────────────────────────────────────────────

export interface HttpRequest {
  /** Per-request id — useful for logging; generated by the server. */
  requestId: string;
  method: string;
  path: string;
  /** Lowercased header names. `host`, `content-type`, etc. */
  headers: Readonly<Record<string, string>>;
  /** Parsed JSON body when Content-Type is application/json; raw text otherwise; null on empty body. */
  body: unknown;
}

export interface HttpResponse {
  status: number;
  /** JSON-serialized if present. */
  body?: unknown;
}

export type HttpHandler = (req: HttpRequest) => Promise<HttpResponse>;

export interface HttpTriggerConfig {
  /** `"host:port"` (e.g. `"127.0.0.1:7080"`). Host is required — no binding to all interfaces. */
  bind: string;
  /** If present, requires `Authorization: Bearer <token>`; token read from `process.env[authTokenEnv]` at start. */
  authTokenEnv?: string;
  handler: HttpHandler;
  logger?: Logger;
}

// ─────────────────────────────────────────────────────────────────────────
// Cron trigger
// ─────────────────────────────────────────────────────────────────────────

export interface CronTick {
  /** Same `jobName` passed in config — lets the handler distinguish jobs when it's registered for many. */
  jobName: string;
  /** Wall-clock time the tick fired. */
  firedAt: Date;
}

export type CronHandler = (tick: CronTick) => Promise<void>;

export interface CronTriggerConfig {
  /** Named job — surfaces in logs and the CronTick payload. Must be unique per daemon for clean telemetry. */
  jobName: string;
  /** Standard 5-field cron expression (`"m h dom mon dow"`). Parsed by croner. */
  schedule: string;
  handler: CronHandler;
  logger?: Logger;
  /** Optional timezone (e.g. `"UTC"`, `"America/New_York"`). Default: system local. */
  timezone?: string;
}

// ─────────────────────────────────────────────────────────────────────────
// Shared lifecycle
// ─────────────────────────────────────────────────────────────────────────

export interface TriggerSource {
  start(): Promise<void> | void;
  stop(): Promise<void> | void;
}
